default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: EM_API_DEV
  username: <%= ENV['EM_API_DB_USERNAME'] %>
  password: <%= ENV['EM_API_DB_PASSWORD'] %>
  host: localhost
  port: 5432
test:
  <<: *default
  database: EM_API_TEST
  username: <%= ENV['EM_API_DB_USERNAME'] %>
  password: <%= ENV['EM_API_DB_PASSWORD'] %>
production:
  <<: *default
  database: EM_API_PRO
  username: <%= ENV['EM_API_DB_USERNAME'] %>
  password: <%= ENV['EM_API_DB_PASSWORD'] %>